### ISSUE TITLE
Custom Configuration

### ISSUE THREAD

**Issue by mastersign** [Maximus5/conemu-inside#15]
I'm really impressed by your work on ConEmu and the windows forms control. I was looking a long time for such a neat solution.

For the windows forms control, I wish there would be a way to provide a custom configuration. Maybe provide a property `ConfigurationSource` of type `Func<Stream>` on `ConEmuStartInfo` and use it in `ConEmuSession.Init_MakeConEmuCommandLine_EmitConfigFile` to load the configuration template. If none is provided you can still fall back to the template resource.

If it helps, I can prepare a pull request.

**Comment by hypersw** [comment]
Maybe make it `XmlDocument` rather? This way it would also early-check that the config file is at least a valid XML.

**Comment by mastersign** [comment]
Good Idea. Much simpler.
