### ISSUE TITLE
Remove Min, Max and Close button

### ISSUE THREAD

**Issue by Therena** [Maximus5/conemu-inside#23]
I would like to have the possibility to change the visibility of the Mn, Max and close buttons of the conemu panel.

Currently I use a "hack" for this which seems not to work all the time.

This will disable them in most of the times:
int cbMultiShowButtons = 2549;
ExecuteGuiMacro("SetOption(\"Check\", " + cbMultiShowButtons + ", 0)");
ExecuteGuiMacro("SetOption(\"Check\", " + cbMultiShowButtons + ", 1)");

**Comment by Maximus5** [comment]
Hm. Do you really need [toolbar](https://conemu.github.io/en/ToolBar.html) in the inside mode at all?

**Comment by hypersw** [comment]
Currently, the control does not have an option to enable the toolbar at all, and always has it hidden, so I cannot immediately see the scope of these min/max/close button options.

**Comment by Therena** [comment]
> Hm. Do you really need toolbar in the inside mode at all?
Yes would be nice.
It is used to create task, open cofing, open new console tabs.
If I disable your toolbar I have to implement my own toolbar which I think isn't nessecary.

> Currently, the control does not have an option to enable the toolbar at all, and always has it hidden,
> so I cannot immediately see the scope of these min/max/close button options.
The toolbar can be enable using configuration (XML file).

**Comment by Therena** [comment]
I would like to have or keep the green part of the header but disable the red part of the header.

![image](https://cloud.githubusercontent.com/assets/18515874/15336931/4b95e7c8-1c79-11e6-9788-0d65df0ce173.png)

**Comment by Therena** [comment]
What I would like to have is this:

![image](https://cloud.githubusercontent.com/assets/18515874/15337476/4e1531a4-1c7c-11e6-91f8-0a4fa9e50839.png)

Calling this often works:
`int cbMultiShowButtons = 2549;`
`ExecuteGuiMacro("SetOption(\"Check\", " + cbMultiShowButtons + ", 0)");`
`ExecuteGuiMacro("SetOption(\"Check\", " + cbMultiShowButtons + ", 1)");`

But unfortunately not always.

**Comment by hypersw** [comment]
Tabs under tabs %-)

**Comment by Therena** [comment]
Hi,

yes in the screenshot it looks like "Tabs under tabs" which I know is from design and usability not a good choise.

But keep in mind the Visual Studio tool window isn't a normal tab.
In the screenshot it is only a tab because I as user decided to dock the window within a tab system.
I can also e.g. don't dock it at all to any parent window or dock it to some position there isn't a tab control.

So the "Tab under tabs" was not a design decision, it was a end-user decision.

But I'm fully with you that it looks ugly if it is docked to a tab control :)

Regards,
David

**Comment by Therena** [comment]
Hi,

furthermore if I create it that way the user have within Visual Studio exactly the same look and feel of conemu as outside of Visual Studio. So they don't have to search for settings, open tabs, ... in the anyway very crowded Visual Studio controls.

The users can use conemu then just in the same way as they would use it outside of Visual Studio.

Regards,
David

**Comment by Maximus5** [comment]
Actually, actions "Create new tab" and "Switch between tab" may be executed from StatusBar. Therefore I think that TabBar is not useful in VS, especially when there is only one tab.

**Comment by Therena** [comment]
Which part is StatusBar and which is TabBar?

**Comment by Maximus5** [comment]
* http://conemu.github.io/en/TabBar.html
* http://conemu.github.io/en/StatusBar.html

**Comment by Therena** [comment]
I agree if there is only one tab the TabBar isn't useful.
But I think it is just more easy to work with tabs within a TabBar, than using the StatusBar for this.
I think that users are also more accustomed to work with tabs in tab bars.

I think, I don't completely got the point why it is a problem to show the TabBar here.

The only thing I would like to have is an option to disable the Min/Max/Close buttons.
Exactly the same as it is made in the standard conemu window.

Why the buttons are shown in the embedded window but not in the standard window?

**Comment by Maximus5** [comment]
Min/Max/Close buttons must not be present in Inside mode. Just wait for next ConEmu build.

**Comment by Therena** [comment]
Sounds great. Thanks for the help.

**Comment by Therena** [comment]
The buttons are gone.
Thanks for the help.
