### ISSUE TITLE
Conemu crash while run it within Visual Studio extension

### ISSUE THREAD

**Issue by Therena** [Maximus5/conemu-inside#28]
Hi,

I got a dump of a conemu crash in an bug report for the Visual Studio extension:
https://github.com/Therena/ConEmuIntegration/issues/3

I cannot analyze it because haven't any debug symbols for conemu.
Could you please check the dumps and that I know how to fix this or what is going wrong there.

Thanks.

Regards,
David

**Comment by Therena** [comment]
After a quick chat on twitter with Maximus5, I got the debugging symbols.
So I can do the investigation by may own.
Thanks.

**Comment by Maximus5** [comment]
If the asserion can appear in current stable, it would be nice to know the conditions. It must be fixed in ConEmu too.

**Comment by Therena** [comment]
Hi,

This can also happen with current stable version if the conemu window is resized to a size of 0.
But this is no normal situation for the not embedded conemu.

It is strange that a visual studio panel can have that size, but it seems so that it happens from time to time.

My fix for this was that a have set a minimum width and height for the panel which displays the conemu. The it never can happen that it has the size 0.

The position of the assert is in:
ConEmu64!CVConGroup::PreReSize

There you check if the width and height is 0 then male a assert and set the size to some default.

Regards,
David
