### ISSUE TITLE
Elevated conemu session

### ISSUE THREAD

**Issue by gaza3g** [Maximus5/conemu-inside#34]
Is there a way( or a configuration that I can add) to open a new conemu window inside VS that has Admin privileges?

**Comment by Maximus5** [comment]
It depends on how do you run ConEmu.
You may either start elevated Task, e.g. {cmd (Admin)}, when you start ConEmu
Or start new elevated console when ConEmu is started.
http://conemu.github.io/en/LaunchNewTab.html

**Comment by gaza3g** [comment]
Understood. Thank you so much!
