### ISSUE TITLE
Compatability issue with csc.exe and ConEmu Inside (but not ConEmu)

### ISSUE THREAD

**Issue by AndrewBragdon** [Maximus5/conemu-inside#38]
When running the C# compiler (CSC.exe) from inside ConEmu Inside demo app it crashes. However when running CSC.exe from the main ConEmu release it works.

Here are the repro steps:

- Download the latest version of ConEmuInside
- Run the ConEmuInside demo app
- Initialize a {powershell} console
- Paste this command into the terminal: 

C:\Windows\Microsoft.NET\Framework64\v4.0.30319\csc.exe

- Hit enter to run

Expected: CSC.exe runs and outputs normally
Actual: CSC.exe crashes - see attached screenshot

![image](https://cloud.githubusercontent.com/assets/5231939/25558047/abe89e34-2cd3-11e7-8585-cc3f8b219de8.png)

**Comment by Maximus5** [comment]
ConEmu binaries in the inside demo are rather old. Just update them.

**Comment by AndrewBragdon** [comment]
Good idea.  I tried changing the path to the EXE to be ConEmuPack.161206.  Unfortunately csc.exe still crashes.  I tried both 32-bit and 64-bit.  Interesntly, if I run ConEmu64.exe from the same pack, it actually works fine:

![image](https://cloud.githubusercontent.com/assets/5231939/25558367/1082e268-2cda-11e7-8396-d288b96fa73f.png)

I also tried coyping the ConEmu executables directly into the bin/Debug/ConEmu folder for ConEmu Inside and I got the same crashes.

Is it possible there is something specific with ConEmu Inside that is causing the problem?

**Comment by Maximus5** [comment]
Width/height of the console?

**Comment by AndrewBragdon** [comment]
Hmm, I tried different widths/heights but it still seems to be crashing.  Any other ideas?

**Comment by Maximus5** [comment]
Finally. I found the problem and it is [the bug in csc.exe](https://stackoverflow.com/a/30957783/1405560).

csc.exe crashes **always** if the console output codepage is UTF-8. So it does not depends on ConEmu at all. If you want to use it, just call `chcp 850` or something like this. But if you call `chcp 65001` before csc, it would crash every time even in bare conhost window.

It would be easy to find it by comparing [Settings/Info](https://conemu.github.io/en/SettingsInfo.html) in working and not working ConEmu instances.

@miniksa I'm not sure, but may be you can check this?
