### ISSUE TITLE
conemu embedded in vscode?

### ISSUE THREAD

**Issue by Tulkis** [Maximus5/conemu-inside#40]
Hi, Is there any w ay to integrate embedded conemu with vscode?
Thanks in advance.

**Comment by Maximus5** [comment]
I didn't create any extension for vscode.
There is extension for Visual Studio, but it will not work in code I think.

**Comment by Tulkis** [comment]
Thanks for the quick response, do you have any intention to develop it in the future?

**Comment by Maximus5** [comment]
I have no intention to implement specific extensions. Instead I'm focused on reusable modules like ConEmu.core for .net

**Comment by Tulkis** [comment]
Ok @Maximus5 ,
Thank you very much for your work with conemu, It is the best console emulator I never found.
Regards,
Eduard.
