### ISSUE TITLE
Intermittent failure - Can't create a new virtual console!

### ISSUE THREAD

**Issue by IanBAdams** [Maximus5/conemu-inside#41]
I’m looking for some help. I’m experiencing an intermittent problem with ConEmu. A brief summary:

- I have 5 desktop and one laptop computers for the various members of my family.
- All have Windows 10 Pro installed, version 1709 (OS Build 16299.371).
- I use scripts to perform a variety of maintenance tasks overnight.
- I’ve been using ConEmu to run my scripts minimised. 
- I’m using the ConEmu portable version, 180409 [64].
- The script I’m having a problem with is run via Task Scheduler at logon. It’s a windows batch wrapper script which calls a powershell script.
- My computers are left powered on but either sleep or hibernate after a period of inactivity. So while the problem script runs at logon this follows a restart.
- I’ve had no problems with all my other scripts so I suspect it is something to do with the logon / restart.
- The command line I use to run the script from Task Scheduler is 
C:\_Software\Portable_Software\ConEmu\ConEmu64.exe  -min -log -run C:\_Software\Scripts\Prod\Control\IA_StartLogonSoftware.bat Scheduled -cur_console:n
- This intermittently fails with:

Can't create a new virtual console!
{CConEmuMain::CreateStartupConsoles}
Command:
C:\_Software\Scripts\Prod\Control\IA_StartLogonSoftware.bat Scheduled -cur_console:n

- As a workaround I have another script that runs later that checks if the failing script has completed successfully. If not it will rerun the failing script (omitting the -log switch).
- Of the three log files only the ConEmu-gui one seems to have been created.
- See the following link https://1drv.ms/u/s!Alefy_LcLA_3jzMfS71EPiDDpNSV for a copy of the log file for the problem script. I’ve also included a copy of a ConEmu-gui log file from one of my other computers where the problem script ran successfully. 
ConEmu-gui-4408.log is the log file for the script which fails. ConEmu-gui-4736.log is the log file for the script which was OK.

Any ideas on what is going wrong and how I can avoid the problem? I suspect if I add a long enough delay into Task Scheduler this would avoid the problem but I would prefer to avoid this if possible.

Let me know if you need any more information.

Many thanks
Ian Adams

**Comment by IanBAdams** [comment]
1. OK, I'll update to the latest version and report back if the issue still occurs.
2. Typo.

I guess that means I shouldn't have created the issue here. Where should I have created it?

**Comment by Maximus5** [comment]
Yes, I prefer issues in proper place

**Comment by IanBAdams** [comment]
Closing pending install of later version and retesting. If problem reoccurs will reopen within ConEmu project.
