### ISSUE TITLE
Error in the VS extension

### ISSUE THREAD

**Issue by Therena** [Maximus5/conemu-inside#42]
Hi,

I have a user of the VS extension which gets an error popup from ComEmu which I never saw before.
Maybe you have a clue what is going wrong there …

Text the user posted:

------------------------------------------------------------------------

I have 64 bit version of ConEmu installed. I installed the extension in VS 2017 Professional. I have set the path but when I try to open conemu window from VS - it shows a black console window with this error.

Unknown switch: /InsideWnd
Unknown switch: /NoKeyHooks
Unknown switch: /LoadCfgFile

Press Enter or Esc to close console, or wait...

Also it's not opening within Visual Studio.

------------------------------------------------------------------------

https://marketplace.visualstudio.com/items?itemName=DavidRoller.ConEmuIntegration#review-details

Thanks.

Regards,
David

**Comment by Maximus5** [comment]
Looks like these switches were passed to started shell.
First of all you should be sure user have installed latest ConEmu ([Old Builds](https://conemu.github.io/en/OldBuild.html))
But most probably user put these switches into startup command in your extension settings.

**Comment by vsha041** [comment]
Hi Maximums5 - Here is a screenshot of the issue. What do you think? I have latest version of ConEmu installed.
![untitled](https://user-images.githubusercontent.com/25815202/41391502-29fd544a-6fef-11e8-8f97-b28f7a40f8db.png)

**Comment by vsha041** [comment]
And this is how the process is started - as you said. But why it is starting like this?

![untitled2](https://user-images.githubusercontent.com/25815202/41391770-b908d1f4-6ff0-11e8-8d1e-79b430b20df7.png)

**Comment by vsha041** [comment]
It works now. I gave a config xml file in the settings option. It works after removing it. But the very firs time I got this error. I didn't get it again.

---------------------------
ConEmu 180528 [64]
---------------------------
Assertion: ConEmu 180528 [64] PID=10632, TID=650464
C:\Program Files\ConEmu\ConEmu64.exe
conemu\src\conemu\vcongroup.cpp:5248
-----------------------
rcCon.right && rcCon.bottom
-----------------------
Press <Ignore> to continue your work.
Press <Abort> to throw exception, ConEmu will be terminated!
Press <Retry> to copy text information to clipboard

and report a bug (open project web page).
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by Maximus5** [comment]
Extension starts `ConEmuC64.exe` instead of `ConEmu64.exe`! Obviously they are absolutely different executables and you get the error.
Extension should check for valid name, if it allows user to select executable instead of installation folder.

**Comment by vsha041** [comment]
Maximus5 - Please close this ticket as it is working fine.

**Comment by Therena** [comment]
> Extension should check for valid name, if it allows user to select executable instead of installation folder.
For your interest:
I added some path validation to the newest release of the extension-
