### ISSUE TITLE
Error message when "handling" ttf files

### ISSUE THREAD

**Issue by pmiossec** [Maximus5/conemu-inside#46]
ConEmu show strange error messages when you do some things with ttf files which are not necessary font files. (See https://github.com/gitextensions/gitextensions/issues/7348#issuecomment-545898758)

Is it possible to disable this behavior?

**Comment by Maximus5** [comment]
I don't remember why fonts are loaded from working directory.
This code was added almost 9 years ago ;)
https://conemu.github.io/en/Whats_New_1.html#build-101108

I think that it may be deleted. Can you please create an issue on the main issue tracker?

**Comment by vedraven** [comment]
I used this function. Why turn it off like that? You could optionally leave the fonts or move them to another folder. Please return the functionality back.
