### ISSUE TITLE
Ping Command Output Won't Get into the ANSI Stream

### ISSUE THREAD

**Issue by hypersw** [Maximus5/conemu-inside#6]
```
ping ya.ru
```

The ANSI stream log is getting no content, the host gets no text for parsing the result.

**Comment by Maximus5** [comment]
Are you sure? There were fixes about that lately.

**Comment by hypersw** [comment]
As I've filed no issue before, I couldn't quite track its status. I'll have it re-checked.

**Comment by Maximus5** [comment]
151217?

**Comment by hypersw** [comment]
Works now.
