### ISSUE TITLE
GuiMacro GetInfo Root Returns ExitCode=259 When Process Is Running

### ISSUE THREAD

**Issue by hypersw** [Maximus5/conemu-inside#9]
This value can't be used for checks because the real exit code of the process might just match.
So I believe this field should either be omitted for a running process altogether, or be set to a value outside of the valid retvals range.

**Comment by Maximus5** [comment]
259 is well known value STILL_ACTIVE, returned by GetExitCodeProcess|Thread. Applications should avoid to return it.
I consider it's admissible. But of course, you should to check Status to be sure.
